import React, { SetStateAction } from "react";
import { Socket } from "socket.io-client";
export interface User {
  id: string;
  email: string;
  name: string;
  imageUrl: string | null;
  createdAt: string;
  workOSId: string;
}
export type LoggedInUser = {
  isAuthenticated: boolean;
  user: User | null;
};
export type AuthContextType = {
  loggedInUser: LoggedInUser;
  setLoggedInUser: React.Dispatch<SetStateAction<LoggedInUser>> | null;
};
export interface SocketContextType {
  socket: Socket | null;
  // setSocket: React.Dispatch<SetStateAction<Socket | null>> | null;
}

export interface ConversationContextType {
  allMessages: Message[];
  messagesEndRef: React.RefObject<HTMLDivElement>;
  currentConversation: Conversation | null;
  currentLoggedInMember: Member | null;
  setCurrentConversation: React.Dispatch<
    SetStateAction<Conversation | null>
  > | null;
}

export interface Message {
  id: string;
  body: string;
  conversationId: string;
  senderId: string;
  createdAt: string;
  updatedAt: string;
  sender: Sender;
}

export interface Sender {
  id: string;
  joinedAt: string;
  userId: string;
  conversationId: string;
  role: string;
  user: User;
}
// Generated by https://quicktype.io

export interface Conversation {
  id: string;
  isGroup: boolean;
  groupTitle: null;
  type: string;
  createdAt: string;
  updatedAt: string;
  members: Member[];
}

export interface Member {
  id: string;
  joinedAt: string;
  userId: string;
  conversationId: string;
  role: string;
  user: User;
}
